packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'esmodules/*'
  - 'apps/*'
  - 'apis/*'
  - 'playing/*'

  # all packages in subdirs of components/
  - 'projects/**'
  # - components/**

  # exclude packages that are inside test directories
  # - !**/test/**
